name: comparative-pinns-bem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.3
  - numpy==1.26.4
  - scipy==1.13.1
  - matplotlib==3.8.4
  - pyDOE==0.3.8 
  - pytorch==2.3.0
  - pandas==2.2.2
  - imageio==2.34.1
  - svgutils==0.3.4
  - optuna==4.5.0
  - plotly==6.0.1
  - nbformat==5.10.4
  - joblib==1.5.1
  - botorch==0.15.1
  - seaborn==0.13.2