# Makefile to run Python scripts in sequence
.PHONY: all run_01_analytical_solution

# Define default target
all: run_01_analytical_solution

# Target to run analytical_solution.py
run_01_analytical_solution:
	@echo "=============================================="
	@echo ">>> START: Analytical Solution Workflow"
	@echo "=============================================="

	@echo "Running analytical_solution.py..."
	@python analytical_solution.py
	@echo "Finished analytical_solution.py..."

	@echo "=============================================="
	@echo ">>> END: Analytical Solution Workflow"
	@echo "=============================================="


